---
name: Dependency Review

on: # yamllint disable-line rule:truthy
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2 # tag=v2.21.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.securityscorecards.dev:443
            github.com:443

      - name: Checkout Repository
        uses: actions/checkout@v5 # tag=v7.0.1

      - name: Dependency Review
        uses: actions/dependency-review-action@v5 # tag=v5.0.0
